## Distributed Learning

In [1]:
import torch
import torch_xla
import torch_xla.core.xla_model as xm

In [2]:
xm.get_xla_supported_devices()

['xla:0',
 'xla:1',
 'xla:2',
 'xla:3',
 'xla:4',
 'xla:5',
 'xla:6',
 'xla:7',
 'xla:8',
 'xla:9',
 'xla:10',
 'xla:11',
 'xla:12',
 'xla:13',
 'xla:14',
 'xla:15',
 'xla:16',
 'xla:17',
 'xla:18',
 'xla:19',
 'xla:20',
 'xla:21',
 'xla:22',
 'xla:23',
 'xla:24',
 'xla:25',
 'xla:26',
 'xla:27',
 'xla:28',
 'xla:29',
 'xla:30',
 'xla:31']

# trunc_normal_ reproduce

In [1]:
import torch
# torch.cuda.is_available()

In [2]:
import torch
import torch_xla
import torch_xla.core.xla_model as xm
from torch import nn
import math
dim = 32
std = 1.0 / math.sqrt(dim)
# device="xla:0"
# device='cuda:0'
device=xm.xla_device()
in_proj = nn.Linear(32, 64, bias=False, device=device)
print(in_proj.weight)
torch.nn.init.trunc_normal_(in_proj.weight, std=std, a=-3 * std, b=3 * std)
print(in_proj.weight)

2024-07-01 22:08:11.000524:  212750  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-01 22:08:11.000526:  212750  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.13.72.0+78a426937/MODULE_17120691043056328803+d41d8cd9/model.neff. Exiting with a successfully compiled graph.
Parameter containing:
tensor([[ 0.0552, -0.1549, -0.0455,  ..., -0.1197, -0.1469, -0.0273],
        [ 0.0421, -0.0083,  0.0758,  ...,  0.1315,  0.1711,  0.0695],
        [-0.1300, -0.1669, -0.0734,  ...,  0.1483,  0.0258, -0.0425],
        ...,
        [-0.0146,  0.0533, -0.1747,  ..., -0.0572,  0.1351,  0.0212],
        [-0.0631,  0.1442,  0.0390,  ...,  0.0817, -0.0955, -0.0974],
        [-0.0907, -0.1105, -0.1150,  ...,  0.1622,  0.0531, -0.1762]],
       device='xla:0', requires_grad=True)
2024-07-01 22:08:11.000664:  212750  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-01 22:08:11.000667:  212750  INF

In [13]:
a = torch.rand(2, 32, device=device, requires_grad=True)

In [14]:
b = in_proj(a)


In [15]:
b

2024-07-01 22:14:00.000004:  212750  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-01 22:14:00.000007:  212750  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/d773e7a6-24c9-425b-866b-4a630b8706e3/model.MODULE_13899153033736678188+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/d773e7a6-24c9-425b-866b-4a630b8706e3/model.MODULE_13899153033736678188+d41d8cd9.neff --verbose=35
.
Compiler status PASS


tensor([[7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282,
         7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282,
         7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282,
         7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282,
         7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282,
         7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282,
         7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282, 7.3282,
         7.3282],
        [8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943,
         8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943,
         8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943,
         8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943,
         8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943, 8.0943,
         8

In [16]:
c = torch.rand(2, 64)


In [17]:
loss = torch.nn.L1Loss()
d = loss(b, c)

In [18]:
d.backward()

In [19]:
a.grad

2024-07-01 22:14:07.000258:  212750  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-01 22:14:07.000261:  212750  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/78141499-4c41-45e3-b68e-8ff7c43921e1/model.MODULE_317728922451237312+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/78141499-4c41-45e3-b68e-8ff7c43921e1/model.MODULE_317728922451237312+d41d8cd9.neff --verbose=35
.
Compiler status PASS


tensor([[0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656,
         0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656,
         0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656,
         0.2656, 0.2656, 0.2656, 0.2656, 0.2656],
        [0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656,
         0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656,
         0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656, 0.2656,
         0.2656, 0.2656, 0.2656, 0.2656, 0.2656]], device='xla:0')

# SwiGLU-pytorch

In [2]:
import torch
import torch.nn.functional as F
from torch import nn
import torch_xla.core.xla_model as xm
class Params:
    te_device = xm.xla_device()
    dim = 64

In [3]:
class SwiGLUTorch(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, args: Params = Params, bias=True):
        super().__init__()
        self.w12 = nn.Linear(in_dim, 2 * hidden_dim, bias=bias, device=args.te_device)
        # self.w12 = nn.Linear(in_dim, 2 * hidden_dim, bias=bias)
        self.w3 = nn.Linear(hidden_dim, out_dim, bias=bias, device=args.te_device)
        # self.w3 = nn.Linear(hidden_dim, out_dim, bias=bias)

    def forward(self, x):
        gate, x = self.w12(x).chunk(2, dim=-1)
        x = F.silu(gate) * x
        return self.w3(x)

In [4]:
args = Params()
hidden_dim = 256 * ((int(2 * 4 * args.dim / 3) + 256 - 1) // 256)

In [5]:
# feed_forward = SwiGLUTorch(args.dim, hidden_dim, args.dim, bias=False)
feed_forward = SwiGLUTorch(args.dim, hidden_dim, args.dim, bias=True)

In [6]:
input_data = torch.rand(2, args.dim, device=args.te_device, requires_grad=True)

In [7]:
out_res = feed_forward(input_data)

In [8]:
print(out_res)

2024-07-02 16:17:43.000223:  264768  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 16:17:43.000225:  264768  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/f6e4c1d2-3346-42ea-97c4-4f33504117cd/model.MODULE_13096779559885804376+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/f6e4c1d2-3346-42ea-97c4-4f33504117cd/model.MODULE_13096779559885804376+d41d8cd9.neff --verbose=35
.
Compiler status PASS
tensor([[-5.4396e-02,  2.4788e-03, -3.6057e-02, -1.0108e-01, -1.1356e-02,
          2.1630e-01,  5.1195e-02,  2.5060e-02, -1.2509e-02, -2.9625e-02,
         -1.6905e-02, -8.6524e-03,  8.2070e-02, -1.3243e-02,  5.1400e-02,
          1.2978e-02, -8.5661e-02, -1.2061e-02,  1.2263e-02, -6.8452e-02,
         -5.0165e-02,  3.9816e-02,  4.1906e-02, -1.1900e-01, -1.8282e-02,
          6.6551e-03,  2.8953e-02,  1.3302e-02,  1.0320e-01,  1.7242e-02,
         -

### First minimal block - confirmed bug existed

In [9]:
import torch
import torch.nn.functional as F
from torch import nn
import torch_xla.core.xla_model as xm
class Params:
    te_device = xm.xla_device()
    dim = 64


class SwiGLUTorch(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, args: Params = Params, bias=True):
        super().__init__()
        self.w12 = nn.Linear(in_dim, 2 * hidden_dim, bias=bias, device=args.te_device)
        self.w3 = nn.Linear(hidden_dim, out_dim, bias=bias, device=args.te_device)
    def forward(self, x):
        gate, x = self.w12(x).chunk(2, dim=-1)
        x = F.silu(gate) * x
        return self.w3(x)


args = Params()
hidden_dim = 256 * ((int(2 * 4 * args.dim / 3) + 256 - 1) // 256)

# feed_forward = SwiGLUTorch(args.dim, hidden_dim, args.dim, bias=False)
feed_forward = SwiGLUTorch(args.dim, hidden_dim, args.dim, bias=True)

input_data = torch.rand(2, args.dim, device=args.te_device, requires_grad=True)

out_res = feed_forward(input_data)

print(out_res)

2024-07-02 16:21:43.000300:  264768  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 16:21:43.000302:  264768  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/d3665e76-36fc-4959-81cc-21acafe435a9/model.MODULE_15793982884432442560+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/d3665e76-36fc-4959-81cc-21acafe435a9/model.MODULE_15793982884432442560+d41d8cd9.neff --verbose=35
.
Compiler status PASS
tensor([[ 0.0041,  0.0943, -0.0168,  0.0420, -0.0077,  0.0305, -0.0181,  0.0230,
         -0.0666, -0.0475, -0.0149,  0.0162, -0.0127,  0.0305, -0.0040,  0.0311,
         -0.0414, -0.1199, -0.0031, -0.0465,  0.0716, -0.0505, -0.0013, -0.0252,
         -0.0435, -0.0330, -0.0317, -0.0164,  0.0551, -0.0207, -0.0724, -0.0230,
          0.0215, -0.0102, -0.0254,  0.0936,  0.0846,  0.0255,  0.0509, -0.0537,
         -0.0049,  0.0553, -0.0336, -0.0329, -0.0

In [10]:
import torch
import torch.nn.functional as F
from torch import nn
import torch_xla.core.xla_model as xm
class Params:
    te_device = xm.xla_device()
    dim = 64


class SwiGLUTorch(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, args: Params = Params, bias=True):
        super().__init__()
        self.w12 = nn.Linear(in_dim, 2 * hidden_dim, bias=bias, device=args.te_device)
        self.w3 = nn.Linear(hidden_dim, out_dim, bias=bias, device=args.te_device)

    def forward(self, x):
        gate, x = self.w12(x).chunk(2, dim=-1)
        x = F.silu(gate) * x
        return self.w3(x)


args = Params()
hidden_dim = 256 * ((int(2 * 4 * args.dim / 3) + 256 - 1) // 256)

feed_forward = SwiGLUTorch(args.dim, hidden_dim, args.dim, bias=False)
# feed_forward = SwiGLUTorch(args.dim, hidden_dim, args.dim, bias=True)

input_data = torch.rand(2, args.dim, device=args.te_device, requires_grad=True)

out_res = feed_forward(input_data)

print(out_res)

2024-07-02 16:21:58.000089:  264768  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 16:21:58.000091:  264768  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/db98c2ca-6d7e-4c6a-bac7-1709e056f91e/model.MODULE_12445586597400423240+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/db98c2ca-6d7e-4c6a-bac7-1709e056f91e/model.MODULE_12445586597400423240+d41d8cd9.neff --verbose=35
.root = /usr/lib/python3.10/multiprocessing/process.py
root = /usr/lib/python3.10/multiprocessing
root = /usr/lib/python3.10
root = /usr/lib
root = /usr

2024-07-02 16:22:00.000153:  264768  ERROR ||NEURON_CC_WRAPPER||: Failed compilation with ['neuronx-cc', 'compile', '--target=trn1', '--framework=XLA', '/tmp/ubuntu/neuroncc_compile_workdir/db98c2ca-6d7e-4c6a-bac7-1709e056f91e/model.MODULE_12445586597400423240+d41d8cd9.hlo_module.pb', '--output', '/tmp/ubuntu/neuroncc_com

: 

### Minimize the block - bias=False to identify the buggy place.

In [1]:
import torch
import torch.nn.functional as F
from torch import nn
import torch_xla.core.xla_model as xm
class Params:
    te_device = xm.xla_device()
    dim = 64

In [2]:
args = Params()
in_dim = args.dim
hidden_dim = 256 * ((int(2 * 4 * args.dim / 3) + 256 - 1) // 256)
out_dim = args.dim

bias = False
# bias = True

w12 = nn.Linear(in_dim, 2 * hidden_dim, bias=bias, device=args.te_device)
# w3 = nn.Linear(hidden_dim, out_dim, bias=bias, device=args.te_device)

input_data = torch.rand(2, args.dim, device=args.te_device, requires_grad=True)
x = input_data

# Feed forward
gate, x = w12(x).chunk(2, dim=-1)
# x = F.silu(gate) * x
# out_res = w3(x)

print(x[0][0])

2024-07-02 20:50:10.000477:  284431  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 20:50:10.000479:  284431  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.13.72.0+78a426937/MODULE_4744642293627985264+d41d8cd9/model.neff. Exiting with a successfully compiled graph.


tensor(-0.0384, device='xla:0', grad_fn=<SelectBackward0>)


In [3]:
x = input_data
gate, x = w12(x).chunk(2, dim=-1)
gate_res = F.silu(gate)
print("gate res:", gate_res[0][0]) 

gate res: 2024-07-02 20:50:10.000634:  284431  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 20:50:10.000637:  284431  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.13.72.0+78a426937/MODULE_12577992882644976145+d41d8cd9/model.neff. Exiting with a successfully compiled graph.
tensor(-0.0107, device='xla:0', grad_fn=<SelectBackward0>)


In [4]:
x[]

2024-07-02 20:50:13.000666:  284431  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 20:50:13.000669:  284431  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.13.72.0+78a426937/MODULE_12477483825163780359+d41d8cd9/model.neff. Exiting with a successfully compiled graph.


tensor([[-3.8417e-02,  5.4682e-01, -4.2049e-01, -5.7221e-02,  6.1046e-02,
         -4.0124e-01, -3.8767e-01, -3.9029e-01, -4.8341e-02, -1.8044e-01,
          4.7251e-02,  2.4704e-01,  5.0204e-01, -3.4156e-02,  4.7420e-02,
          3.9887e-01,  3.3719e-01, -1.7850e-01,  1.6671e-01,  8.6862e-01,
         -2.8862e-01, -3.0525e-01, -4.4352e-02,  2.6474e-01,  6.5911e-02,
         -6.7675e-02,  2.4921e-01,  1.8104e-01, -1.9953e-01, -4.5766e-02,
          9.1586e-02, -1.1842e-01,  8.1991e-02, -9.6470e-02, -1.1874e-01,
          3.1664e-01, -5.0548e-01, -5.3778e-01,  2.4745e-01, -6.5174e-01,
          4.8625e-02,  5.4527e-02, -1.9364e-02,  2.0371e-02, -3.8894e-01,
         -5.9887e-01,  6.6845e-01, -6.1075e-02, -1.3003e-01, -2.3642e-01,
         -1.2695e-01,  7.7555e-02, -8.6472e-02, -8.9840e-02, -7.0883e-01,
         -1.4807e-01, -5.6849e-01, -8.8331e-02, -4.6134e-01,  1.4206e-01,
         -1.0949e-01,  1.6279e-01, -1.4006e-01, -5.8972e-01,  9.7943e-01,
         -8.7838e-02,  3.2581e-02, -4.

In [4]:
out_res_before_w3 = gate_res * x 
print("out_res_before_w3: ", out_res_before_w3[0][0])

out_res_before_w3:  2024-07-02 19:45:06.000359:  283884  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 19:45:06.000361:  283884  ERROR ||NEURON_CC_WRAPPER||: Got a cached failed neff at /var/tmp/neuron-compile-cache/neuronxcc-2.13.72.0+78a426937/MODULE_2625073130775174431+d41d8cd9/model.neff. Will skip compilation, please set --retry_failed_compilation for recompilation: 
 Failed compilation with ['neuronx-cc', 'compile', '--target=trn1', '--framework=XLA', '/tmp/ubuntu/neuroncc_compile_workdir/d80981b3-de32-4fcc-be1e-732b7040a871/model.MODULE_2625073130775174431+d41d8cd9.hlo_module.pb', '--output', '/tmp/ubuntu/neuroncc_compile_workdir/d80981b3-de32-4fcc-be1e-732b7040a871/model.MODULE_2625073130775174431+d41d8cd9.neff', '--verbose=35']: 2024-07-02T16:47:45Z [TEN404] Internal tensorizer error - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new
.


: 

In [9]:
# out_res_before_w3 = gate_res * x 
# out_res_before_w3 = gate_res + x 
out_res_before_w3 = torch.mul(gate_res, x)
print("out_res_before_w3: ", out_res_before_w3[0][0])

out_res_before_w3:  2024-07-02 18:55:51.000123:  279728  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 18:55:51.000127:  279728  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/3d3272d8-0368-4f3e-9477-c8357193805f/model.MODULE_4606195053616088037+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/3d3272d8-0368-4f3e-9477-c8357193805f/model.MODULE_4606195053616088037+d41d8cd9.neff --verbose=35
.root = /usr/lib/python3.10/multiprocessing/process.py
root = /usr/lib/python3.10/multiprocessing
root = /usr/lib/python3.10
root = /usr/lib
root = /usr

2024-07-02 18:55:53.000202:  279728  ERROR ||NEURON_CC_WRAPPER||: Failed compilation with ['neuronx-cc', 'compile', '--target=trn1', '--framework=XLA', '/tmp/ubuntu/neuroncc_compile_workdir/3d3272d8-0368-4f3e-9477-c8357193805f/model.MODULE_4606195053616088037+d41d8cd9.hlo_module.pb', '--output', '/tmp/ub

: 

In [13]:
w12_T = nn.Linear(in_dim, 2 * hidden_dim, bias=True, device=args.te_device)



In [19]:
w12_T.weight.shape, w12_T.bias.shape

(torch.Size([512, 64]), torch.Size([512]))

#### Bias=True works fine

In [4]:
# Works fine
args = Params()
in_dim = args.dim
hidden_dim = 256 * ((int(2 * 4 * args.dim / 3) + 256 - 1) // 256)
out_dim = args.dim

bias = True

w12 = nn.Linear(in_dim, 2 * hidden_dim, bias=bias, device=args.te_device)
w3 = nn.Linear(hidden_dim, out_dim, bias=bias, device=args.te_device)



input_data = torch.rand(2, args.dim, device=args.te_device, requires_grad=True)
x = input_data

# Feed forward
gate, x = w12(x).chunk(2, dim=-1)
x = F.silu(gate) * x
out_res = w3(x)


print(out_res)

2024-07-02 16:29:10.000899:  265991  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 16:29:10.000901:  265991  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/f1a59657-c2bd-48df-9266-c98d0fb02d6a/model.MODULE_13130582528755289296+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/f1a59657-c2bd-48df-9266-c98d0fb02d6a/model.MODULE_13130582528755289296+d41d8cd9.neff --verbose=35


.
Compiler status PASS
tensor([[ 0.0795,  0.0199,  0.0098,  0.0036, -0.0297,  0.0439,  0.0641,  0.0479,
         -0.0463, -0.0331, -0.0226,  0.0218, -0.0594, -0.0714, -0.0943, -0.0110,
          0.0381,  0.0193, -0.0253, -0.0070, -0.0219,  0.0099,  0.0808, -0.0022,
         -0.0886, -0.0090, -0.0910, -0.0522,  0.0207,  0.0209,  0.0953,  0.0139,
         -0.0214, -0.0464,  0.0444,  0.0960, -0.0146,  0.0019, -0.0395, -0.1116,
          0.0116,  0.0529,  0.0819,  0.0291,  0.0415,  0.0611,  0.0124,  0.0138,
         -0.0146, -0.0398,  0.0770,  0.0370,  0.0348,  0.0694,  0.0095, -0.0007,
          0.0115,  0.0397,  0.0618, -0.0070, -0.0072,  0.0444,  0.0352,  0.0056],
        [ 0.0760, -0.0689, -0.0169,  0.0469, -0.0192,  0.0050,  0.0377,  0.0061,
         -0.0644, -0.0557, -0.0811,  0.0475,  0.0372, -0.0131, -0.0621, -0.0388,
         -0.0027,  0.0351, -0.0085,  0.0346,  0.0186,  0.0548,  0.0062, -0.0252,
         -0.0514, -0.0633, -0.0997, -0.0211,  0.0526,  0.0092,  0.0654,  0.0114,
    

2024-07-02 16:30:58.000386:  266572  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-02 16:30:58.000388:  266572  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/5a269232-1341-4dc8-b8e1-0825636dc043/model.MODULE_5261249125463362669+d41d8cd9.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/5a269232-1341-4dc8-b8e1-0825636dc043/model.MODULE_5261249125463362669+d41d8cd9.neff --verbose=35
.root = /usr/lib/python3.10/multiprocessing/process.py
root = /usr/lib/python3.10/multiprocessing
root = /usr/lib/python3.10
root = /usr/lib
root = /usr

2024-07-02 16:31:00.000300:  266572  ERROR ||NEURON_CC_WRAPPER||: Failed compilation with ['neuronx-cc', 'compile', '--target=trn1', '--framework=XLA', '/tmp/ubuntu/neuroncc_compile_workdir/5a269232-1341-4dc8-b8e1-0825636dc043/model.MODULE_5261249125463362669+d41d8cd9.hlo_module.pb', '--output', '/tmp/ubuntu/neuroncc_compil

: 